### ISSUE TITLE
About CS (C#, F#, and Visual Basic) mirror import SimpleJson, MySql and Newtonsoft report errors

### ISSUE THREAD

**Issue by RanX12** [CodeSignal/dockerfiles#286] opened 2021-02-06 03:29 UTC
@menewman 
Hello, I used your company’s CS docker image (v8.0.1), where CSharp
```cs
using SimpleJson.Reflection;
using MySql.Data.MySqlClient;
using Newtonsoft.Json;
```
These three will report an error, the error message: The type or namespace name `SimpleJson & MySql & Newtonsoft ` could not be found. Are you missing an assembly reference?
 
VB's ```Imports SimpleJson.Reflection``` will report an error.
the error message: 
```vb
warning BC40056: Namespace or type specified in the Imports 'SimpleJson.Reflection' doesn't contain any public member or cannot be found. Make sure the namespace or the type is defined and contains at least one public member. Make sure the imported element name doesn't use any aliases.

Imports SimpleJson.Reflection
        ~~~~~~~~~~~~~~~~~~~~~
```

may I ask what went wrong?

The running command of CSharp is: mcs **.cs && mono ./ **.exe
The running command of VB is: vbc **.vb &7 mono ./ **.exe

Please advise, thank you very much!

**Comment by menewman** [comment] 2021-02-06 03:35
@RanX12 - Hi, I'm going to close this because it's not an issue report but a troubleshooting question. From the compilation commands provided, I think the problem is simply that the given libs or assemblies need to be explicitly referenced in the compilation command. For example, you might want to pass a flag like `-r:MySql.Data.dll` to reference the MySql assembly.

**Closed by menewman** 2021-02-06 03:35 UTC

**Comment by RanX12** [comment] 2021-02-06 04:38
ok, thank you for your reply, mysql and Newtonsoft -r:xxx can be solved, but ```SimpleJson.Reflection``` seems to still not work, I am a novice, so please

**Comment by RanX12** [comment] 2021-02-06 06:33
In docker, no *.dll file related to SimpleJson was found....

**Comment by menewman** [comment] 2021-02-08 20:35
Hi @RanX12 - We don't mention anything about SimpleJson in this repo (i.e., in our C# Dockerfile) because it's not installed here -- I'm guessing you probably saw that import in our application? My recommendation is just not to use SimpleJson -- if you're already able to use Newtonsoft/Json.NET, that should be plenty for JSON-parsing purposes!

**Comment by RanX12** [comment] 2021-02-19 02:44
ok，I was at [support.codesignal.com](https://support.codesignal.com/hc/en-us/articles/360045564313-CodeSignal-Coding-Environment) and saw that you support SimpleJson, if you don’t have any SimpleJson related information in your Dockerfile, how does your Visual Basic import? Please advise, thank you very much for your reply.

![image](https://user-images.githubusercontent.com/46048444/108449988-5ff21800-729f-11eb-8447-daee7972dba1.png)

**Comment by menewman** [comment] 2021-02-19 03:20
Astute observation! Yes, in our application, `SimpleJson` is available; however, it's included separately as part of the overall bundle in which we run user code and isn't installed in this Dockerfile. Unfortunately, that means you won't be able to use it in your example without installing or including it separately.

**Comment by RanX12** [comment] 2021-02-19 03:27
ok, thank you, I found a lot of ```SimpleJson``` in Google. Would you like to ask if you are using this? [SimpleJson link](https://github.com/facebook-csharp-sdk/simple-json/blob/master/src/SimpleJson/SimpleJson.cs)

**Comment by menewman** [comment] 2021-02-19 03:53
It's something like that. 🙂
